---
npmName: '@redhattraining/beeper-ui-client'
npmRepository: http://nexus-infra.apps.ocp4.example.com/repository/npm-hosted/
nullSafeAdditionalProps: true
supportsES6: true
withInterfaces: true
withSeparateModelsAndApi: true
apiPackage: api
modelPackage: model
# typescriptThreePlus: true
